services:
  db:
    container_name: postgres_totem_db
    image: postgres:latest
    volumes:
      - ./postgres:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    restart: always